# MySQL \u6570\u636e\u5e93\u8fde\u63a5\u914d\u7f6e
# \u5148\u6267\u884c sql/CPSC_eFiling_DB_create_tables.sql \u521b\u5efa\u6570\u636e\u5e93\u548c\u8868

db.url=jdbc:mysql://8.211.146.202:3306/CPSC_eFiling_DB?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Tokyo&useSSL=false&allowPublicKeyRetrieval=true
db.user=ID_CPSC_eFiling_DB
db.password=Hu4U9s4FzdmT6CPSC_eFiling_DB$